name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration release
    - name: Pack
      run: dotnet pack NV.UI.Bootstrap --configuration release --version-suffix=ci-$GITHUB_RUN_NUMBER
    - name: Get package name
      run: package_name='ls NV.UI.Bootstrap/bin/release/*.nupkg'
    - name: Publish
      run: dotnet nuget push /NV.UI.Bootstrap/bin/release/${package_name} --api-key ${GITHUB_TOKEN} --source https://nuget.pkg.github.com/nickyvadera/index.json
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
