name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Pack
      run: dotnet pack NV.UI.Bootstrap/NV.UI.Bootstrap.csproj --no-build --configuration release
    - name: Publish
      run: dotnet nuget push NV.UI.Bootstrap/bin/release/NV.UI.Boostrap.1.0.0.nupkg --source https://nuget.pkg.github.com/nickyvadera/index.json
