name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration release
    - name: Pack
      run: dotnet pack NV.UI.Bootstrap --configuration release --version-suffix=ci-$GITHUB_RUN_NUMBER
    - name: Echo package name
      run: ls NV.UI.Bootstrap/bin/release/*.nupkg
    - name: Set package name
      run: echo package_name=$(ls NV.UI.Bootstrap/bin/release/*.nupkg) >> $GITHUB_ENV
    - name: Publish
      run: dotnet nuget push /NV.UI.Bootstrap/bin/release/${{PACKAGE_NAME}} --api-key ${GITHUB_TOKEN} --source https://nuget.pkg.github.com/nickyvadera/index.json
      env:
          PACKAGE_NAME: ${{ env.package_name }}
